import "./globals.css";
import { Inter } from "next/font/google";
import Header from "../components/Navbar/Header.jsx"
import Footer from "../components/Navbar/Footer.jsx"

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Sky Travel",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
  
      <body className={inter.className}>
    
        <Header />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
